"""Generates a Word document summarizing a case: cover/metadata, machines,
artifact summary, findings, AI-assisted analysis (rendered from markdown),
and the audit log. Built with python-docx, no external binary dependency."""
import datetime as dt
import io
import re
from typing import Any

from docx import Document
from docx.shared import Pt, RGBColor
from sqlalchemy.orm import Session

from ..models import Case, Machine, AIMessage, AuditEvent, Finding
from . import csv_importer

_ACCENT = RGBColor(0x8A, 0x6A, 0x2C)  # muted amber, echoes the console's accent color
_DIM = RGBColor(0x60, 0x60, 0x60)


def build_case_report(db: Session, case: Case, generated_by: str) -> bytes:
    machines = db.query(Machine).filter(Machine.case_id == case.id).order_by(Machine.created_at).all()

    doc = Document()
    _style_base(doc)

    _cover_section(doc, case, generated_by)
    _machines_section(doc, case, machines)
    _findings_section(doc, db, case)
    _ai_conversations_section(doc, db, case)
    _activity_log_section(doc, db, case)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _style_base(doc: Document) -> None:
    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)


def _heading(doc: Document, text: str, level: int = 1) -> None:
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.color.rgb = _ACCENT


def _cover_section(doc: Document, case: Case, generated_by: str) -> None:
    title = doc.add_heading(case.name, level=0)
    for run in title.runs:
        run.font.color.rgb = _ACCENT

    meta_lines = [
        ("Reference", case.reference or "--"),
        ("Status", case.status.value),
        ("Case created", case.created_at.strftime("%Y-%m-%d %H:%M UTC")),
        ("Report generated", dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")),
        ("Generated by", generated_by),
    ]
    for label, value in meta_lines:
        p = doc.add_paragraph()
        run = p.add_run(f"{label}: ")
        run.bold = True
        p.add_run(str(value))

    if case.description:
        doc.add_paragraph()
        _heading(doc, "Description", level=2)
        doc.add_paragraph(case.description)

    doc.add_page_break()


def _machines_section(doc: Document, case: Case, machines: list[Machine]) -> None:
    _heading(doc, "Machines", level=1)
    if not machines:
        doc.add_paragraph("No machines have been added to this case.")
        return

    for m in machines:
        _heading(doc, m.label, level=2)
        rows = [
            ("Hostname", m.hostname or "unknown"),
            ("Operating system", m.operating_system or "unknown"),
            ("IP address(es)", ", ".join(m.ip_addresses or []) or "unknown"),
            ("Timezone", m.timezone or "unknown"),
            ("OS install date", m.os_install_date or "unknown"),
            ("Source", f"{m.source_kind or 'unknown'}"
                       + (f" ({m.triage_profile})" if m.triage_profile else "")),
            ("Ingest status", m.status.value),
        ]
        table = doc.add_table(rows=0, cols=2)
        table.style = "Light Grid Accent 1"
        for label, value in rows:
            row = table.add_row().cells
            row[0].text = label
            row[1].text = str(value)

        doc.add_paragraph()
        if m.status.value == "ready":
            _artifact_summary_table(doc, case.id, m)
        doc.add_paragraph()


def _artifact_summary_table(doc, case_id: str, machine: Machine) -> None:
    categories = csv_importer.list_categories(case_id, machine.id)
    categories = [c for c in categories if c["tables"]]
    if not categories:
        doc.add_paragraph("No artifact tables were imported for this machine.")
        return

    p = doc.add_paragraph()
    p.add_run("Artifact summary").italic = True

    table = doc.add_table(rows=1, cols=3)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text, hdr[1].text, hdr[2].text = "Category", "Tables", "Rows"

    for cat in categories:
        total_rows = sum(t["row_count"] for t in cat["tables"])
        row = table.add_row().cells
        row[0].text = cat["label"]
        row[1].text = str(len(cat["tables"]))
        row[2].text = f"{total_rows:,}"


def _findings_section(doc, db: Session, case: Case) -> None:
    _heading(doc, "Findings", level=1)
    findings = (
        db.query(Finding)
        .filter(Finding.case_id == case.id)
        .order_by(Finding.created_at)
        .all()
    )
    if not findings:
        doc.add_paragraph("No findings have been flagged for this case.")
        return

    for f in findings:
        source = ""
        if f.machine_label and f.table_label:
            source = f"{f.machine_label} / {f.table_label}"
        elif f.table_label:
            source = f.table_label

        p = doc.add_paragraph()
        run = p.add_run(f"{f.created_at.strftime('%Y-%m-%d %H:%M UTC')}")
        run.font.color.rgb = _DIM
        if source:
            p.add_run(f"  --  {source}").italic = True
        if f.created_by_username:
            p.add_run(f"  (flagged by {f.created_by_username})").italic = True

        doc.add_paragraph(f.note)

        if f.row_snapshot:
            snap_p = doc.add_paragraph()
            snap_p.add_run("Flagged event: ").bold = True
            snippet = ", ".join(f"{k}={v}" for k, v in list(f.row_snapshot.items())[:6] if v)
            snap_p.add_run(snippet[:300])
        doc.add_paragraph()


def _ai_conversations_section(doc, db: Session, case: Case) -> None:
    _heading(doc, "AI-Assisted Analysis", level=1)
    keys = (
        db.query(AIMessage.conversation_key)
        .filter(AIMessage.case_id == case.id)
        .distinct()
        .all()
    )
    keys = [k[0] for k in keys]
    if not keys:
        doc.add_paragraph("No AI-assisted analysis was recorded for this case.")
        return

    for key in sorted(keys):
        _heading(doc, _describe_conversation_key(key), level=2)
        messages = (
            db.query(AIMessage)
            .filter(AIMessage.case_id == case.id, AIMessage.conversation_key == key)
            .order_by(AIMessage.created_at)
            .all()
        )
        for m in messages:
            label = "Question" if m.role == "user" else "AI response"
            p = doc.add_paragraph()
            run = p.add_run(f"{label}: ")
            run.bold = True
            run.font.color.rgb = _ACCENT if m.role == "assistant" else _DIM
            if m.role == "user":
                doc.add_paragraph(m.content)
            else:
                _render_markdown(doc, m.content)
        doc.add_paragraph()


def _describe_conversation_key(key: str) -> str:
    if key == "broad:case":
        return "Whole-case analysis"
    if key.startswith("broad:"):
        return f"Machine-scoped analysis ({key.split(':', 1)[1][:8]})"
    if key.startswith("table:"):
        parts = key.split(":", 2)
        if len(parts) == 3:
            return f"Table analysis -- {parts[2]} (machine {parts[1][:8]})"
    return key


def _activity_log_section(doc, db: Session, case: Case) -> None:
    _heading(doc, "Case Activity Log", level=1)
    events = (
        db.query(AuditEvent)
        .filter(AuditEvent.case_id == case.id)
        .order_by(AuditEvent.created_at.desc())
        .limit(200)
        .all()
    )
    if not events:
        doc.add_paragraph("No recorded activity for this case.")
        return

    table = doc.add_table(rows=1, cols=4)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text = "When (UTC)", "Who", "Action", "Target"
    for e in events:
        row = table.add_row().cells
        row[0].text = e.created_at.strftime("%Y-%m-%d %H:%M")
        row[1].text = e.username or "system"
        row[2].text = e.action
        row[3].text = e.target_label or (e.target_id or "")


_BOLD_RE = re.compile(r"\*\*(.+?)\*\*")
_ITALIC_RE = re.compile(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)")


def _add_inline_markdown(paragraph, text: str) -> None:
    spans: list[tuple[int, int, str, str]] = []
    for m in _BOLD_RE.finditer(text):
        spans.append((m.start(), m.end(), m.group(1), "bold"))
    for m in _ITALIC_RE.finditer(text):
        if not any(m.start() >= s and m.end() <= e for s, e, _, _ in spans):
            spans.append((m.start(), m.end(), m.group(1), "italic"))
    spans.sort()

    pos = 0
    for start, end, content, kind in spans:
        if start > pos:
            paragraph.add_run(text[pos:start])
        run = paragraph.add_run(content)
        if kind == "bold":
            run.bold = True
        elif kind == "italic":
            run.italic = True
        pos = end
    if pos < len(text):
        paragraph.add_run(text[pos:])


def _render_markdown(doc, markdown_text: str) -> None:
    for raw_line in markdown_text.splitlines():
        line = raw_line.rstrip()
        if not line:
            continue
        heading_match = re.match(r"^(#{1,4})\s+(.*)", line)
        if heading_match:
            _heading(doc, heading_match.group(2), level=min(4, len(heading_match.group(1)) + 2))
            continue
        bullet_match = re.match(r"^[-*]\s+(.*)", line)
        if bullet_match:
            p = doc.add_paragraph(style="List Bullet")
            _add_inline_markdown(p, bullet_match.group(1))
            continue
        numbered_match = re.match(r"^\d+\.\s+(.*)", line)
        if numbered_match:
            p = doc.add_paragraph(style="List Number")
            _add_inline_markdown(p, numbered_match.group(1))
            continue
        p = doc.add_paragraph()
        _add_inline_markdown(p, line)
